### ISSUE TITLE
objective function set up as lambda r: r.mean()

### ISSUE THREAD

**Issue by penguinwang96825** [finlab-python/finlab_crypto#15]
In DH Bailey's paper "The probability of backtest overfitting", they used sharpe ratio as their default objective function.
However, in `fin_crypto` library, objective function was set up as `objective=lambda r: r.mean()`.
Just want to clarify, needn't the default of objective function be set as `objective=lambda r: sharpe_ratio(r)`?

**Comment by koreal6803** [comment]
That's a good point. I will update it when there's time!
