### ISSUE TITLE
vectorbt upgrade

### ISSUE THREAD

**Issue by minggnim** [finlab-python/finlab_crypto#17]
Thanks for sharing this great repo!

I can't help but notice that the version of vectorbt is a bit outdated. I think it'd be very helpful to upgrade it to the latest 0.21.0, which offers enhanced stats and pnl analysis, and many more new features. I've created a pr https://github.com/finlab-python/finlab_crypto/pull/16 to support this. Hopefully you also find it useful. Thanks!

**Comment by koreal6803** [comment]
Thank you for noticing, it has been fixed
