### ISSUE TITLE
TypeError: add_yaxis() in utility.py:171

### ISSUE THREAD

**Issue by AmandaRossimandi** [finlab-python/finlab_crypto#20]
167 figures['entries & exits'] = pd.DataFrame(
    168     {'entries':entries.squeeze(), 'exits': exits.squeeze()})
    169 figures['performance'] = portfolio.cumulative_returns()
--> 171 c, info = chart.chart(ohlcv, overlaps=overlaps,
    172                       figures=figures, markerlines=mark_lines,
    173                       start_date=ohlcv.index[-min(1000, len(ohlcv))], end_date=ohlcv.index[-1], k_colors=k_colors)
    174 c.load_javascript()
    175 if html is not None:
...
    161 # indicators
    162 #################
    164 def is_item(item):

TypeError: add_yaxis() got an unexpected keyword argument 'yaxis_data'

seems due to pyecharts library, you need to update your **utility.py** file to the new pyecharts version that receive '_y_axis_' instead of '_yaxis_data_'

**Comment by EugenioBarattini** [comment]
yeah! the same problem, I confirm. I solved with a downgrade to old versione listed in requirements: pyecharts==1.7.1

but now I've issue about **figure** values defined in the @Strategy code:

_figure = {
    'figures': {
        str(rsi_strategy.timeperiod) + '_rsi': rsi
    }
  }_

no more render the RSI curve, but in the old versione of finlab-crypto, one year ago, it work.

**Comment by AmandaRossimandi** [comment]
me too, I've tested just now and no more render the RSI curve on graph. I've used the same strategy (_rsi.py_) in the strategies folder.

![rsiNOTfigure](https://user-images.githubusercontent.com/63255504/174792646-f9e5512e-06eb-4d16-9883-6cf1ae3c104c.png)

**Comment by koreal6803** [comment]
Thank you for the feedback!
latest working example is here (finlab_crypto==0.2.21):
https://colab.research.google.com/drive/1kfKDgGTGhRvu0Bu2OkIHdKnabCdZa-pe?usp=sharing
