### ISSUE TITLE
Mutable default arguments

### ISSUE THREAD

**Issue by jrycw** [finlab-python/finlab_crypto#4]
```python
class Strategy(object):

    def backtest(self, ohlcv, variables=dict(),
                         filters=dict(), lookback=None, plot=False,
                         signals=False, side='long', cscv_nbins=10,
                         cscv_objective=lambda r: r.mean(), html=None, compounded=True, execution_price='close', **args):
```
There might be a potential issue if using `dictionary` as the default argument for `variables` and `filters`, since `dictionary` is mutable. 

I will argue that using `None` as the default argument might be a safer approach.

**Comment by koreal6803** [comment]
Thanks for the feedback, I updated [ecea8d9](https://github.com/finlab-python/finlab_crypto/commit/ecea8d99c5b5b7567ba2c74b1d2617820773a258) to fixed it.
